server.port: ${PORT:8080}

spring:
  main:
    banner-mode: "off"

keybout:
  latency: 0

logging.level:
  ROOT: INFO

---

spring.profiles: color

spring.output.ansi.enabled: ALWAYS

---

spring.profiles: dev

logging.level:
  com.adeliosys: TRACE
